### ISSUE TITLE
App detecting and using unsupported locale [prev: Different locale (hu) - v1.2.2]

### ISSUE THREAD

**Issue by Shiwo01** [dashnine/PaperBlossoms#179]
Greetings,

Just tried this stuff. Seems great ! Just I have an issue with it :\ 

Created a character, saved. Closed the program. Opened again, tried to load the character.

I got the following message : 

> _"This save file was created with a different locale (hu). Aborting import. To load this save file, you can change your DB locale to hu in C:/Users/Shiwo/AppData/Local/PaperBlossoms/settings.ini and relaunch the application."_

I checked the ini file but it already contained hu : 

[General]
localeDB=hu
savefilepath=C:/Gdrive/L5R
localeUI=hu

Regards,
Shiwo

![L5R_Issue](https://user-images.githubusercontent.com/62264186/76798268-8d049380-67cf-11ea-948c-c1b44d062622.JPG)

**Comment by Shiwo01** [comment]
Note : I tried to set to EN too (either of them and both of them too), neither works

**Comment by dashnine** [comment]
@Shiwo01 : Sorry--just saw this issue (for some reason my inbox didn't get a notification here).  

That looks like the application detected a Hungarian localisation--we obviously don't have any HU localisation at the moment.I'm not sure why it's setting that that way, given that there shouldn't be a file there, so it should fall back to EN.  That said, you should be able to get up and running by setting both of those values to **en**, then creating a new character.  If the old character was created with an 'hu' for some reason, it may be difficult to get it loaded.
`localeDB=en
savefilepath=C:/Gdrive/L5R
localeUI=en`

**Comment by dashnine** [comment]
Outside of getting @Shiwo01 up and running, there may be some bugs here to be investigated regarding how the app is detecting and using locale.

**Comment by dashnine** [comment]
So, do be honest, I can't replicate this, OR find how it could execute in the code.  #208 pushed some changes to translation to make it so that it *should* fail a little more smoothly, but I don't think that would affect this; in main.cpp we actually have an if() that prevents the locale from even being set to a completely arbitrary language, so I'm kind of at a loss.  Only thing I can think is that if the character was created early in the tr process, the locale might have been saved to the character file at first.

Unfortunately closing this one as Could Not Replicate for now; if we cna get some good steps to replicate, can always reopen :)
