### ISSUE TITLE
Empty drop-out list for skills in question 8/conflicted

### ISSUE THREAD

**Issue by mczerwinski** [dashnine/PaperBlossoms#180]
On windows, version 1.2.2m windows version zip from here: https://github.com/dashnine/PaperBlossoms/releases?fbclid=IwAR1s3cCNwIzZzGXgfNhEkfy4W0boHV8Na-cPxwZHyrDShuv507oN72wJh1U

In question 8, about bushido, when choosing confliced there should be a skill list of: 
Commerce, Labor, Medicine, Seafaring, Skulduggery, or Survival. (page 91, main rulebook).

There is nothing, no skills to pick from.

**Comment by dashnine** [comment]
Sorry--just saw this.  This sounds like a localized data problem -- on my system, it's allowing selection.  
1) I assume you've selected the 'conflicted' radio button?  THat *should* populate the box with those skills.
2) Have you done any custom modification to your database or tables?  
3) Are any other boxes missing options?

Steps you can try to troubleshoot, if you don't have custom user tables/descriptions:

- Tools->Open Application Data Directory
- Close Paperblossoms.exe
- Select and delete paperblossoms.db
- Relaunch paperblossoms.exe.  When you launch it, you should receive a prompt saying that the local data is missing or older than the bundled data, and asking if you want to overwrite.  Say 'yes' to copy a fresh database to your system

Does that get you up and running?

**Comment by dashnine** [comment]
Closing due to lack of follow-up.  If you're still running into trouble or observe a similar problem, can reopen this down the line!  Thanks for the report--hopefully you're up and running now. :)

**Comment by tdjc** [comment]
Hey @dashnine, a friend of mine just had the same issue on Mac version, but he managed to fix it - changing language code in settings.ini from PL to EN fixed the dropdown. I suppose your `translate` function returns empty strings for PL (although I don't quite get why only this dropdown is affected).
 https://github.com/dashnine/PaperBlossoms/blob/e47bbd4da758b3e2271ba921091dba69382fb17f/PaperBlossoms/src/newcharwizardpage3.cpp#L101

**Comment by dashnine** [comment]
@tdjc Oh, absolutely.  I *also* don't know what's happening here, but that dropdown is one of a small number of cases in the app where we lean on a hard-coded list of values instead of yanking from the DB, so it may have something to do with how we're calling it.  

Honestly, reading it, I suspect I meant to use Qt's 'tr' function, rather than calling dal->translate.  Or both, depending on the rest of the file.  Based on your feedback, I'll reopen this and mark it as a bug--this looks like it'll be annoying to debug, but easy to fix when we find it. :) Thanks!

For that matter (since it seems you're comfortable in code) let me know if you find a fix before I do, and I'll be happy to test and merge a PR. :-D  Either way, thanks--this should be plenty to get us started chasing this down!

**Comment by tdjc** [comment]
@dashnine Happy to help :) As for coding, you're right, I'm a programmer, but I haven't worked with C++ for a long time (and with Qt at all), so I'm afraid I'll be of little help with fixing the issue :/

**Comment by dashnine** [comment]
Ok, I think I have it chased down.  In that spot, the DAL-> translate option was used--but it could have been either translate function, in this case.  What *is* important is that it has hit on a bug: in the event that a database translation is generated but not populated, dal-translate will return an empty string (when it should instead return the original string).  Should be a quick fix!

**Comment by dashnine** [comment]
Note: this was occurring here because someone originally proposed translating into PL, but never actually ended up providing the translation.  I suspect as we get translations that fall behind, though, that will become more common.
