### ISSUE TITLE
equipment error in Two Heavens Adept. 

### ISSUE THREAD

**Issue by Daeglan** [dashnine/PaperBlossoms#187]
in 2.2.0 it lists Katana or 2 weapons rarity 6 or less. It should be Daisho or 2 weapons.

**Comment by dashnine** [comment]
In this case, that'll be treated as (Katana and Wakizashi) or (Weapon rarity 6 or less, and Weapon rarity 6 or less). Tagging as data bug

**Comment by dashnine** [comment]
On review, the app looks like it's doing it right.  The literal contents should be ((katana) OR (two weapons r6 or lower)) AND Wakizashi.  In this case, since the wakizashi is always present, it isn't shown for selection on the character screen, but will be present in the gear at the end. :)

Thanks for the report, though!
